name: Publish Release
on:
  release:
    types:
      - published
jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Set pre_release
        run: |
          sed -i "s/pre_release=alpha/pre_release=/g" gradle.properties
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: preprocessResources
        run: ./gradlew preprocessResources
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.2
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        with:
          modrinth-id: oQgSAEhD
          modrinth-token: ${{ secrets.MODRINTH }}

          curseforge-id: 454900
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: fabricWrapper/build/libs/!(*-@(dev|sources)).jar
          files-secondary: fabricWrapper/build/tmp/submods/META-INF/jars/!(*-@(dev|sources)).jar

          name: ''

          version-type: release
          changelog: ${{ github.event.release.body }}

          loaders: fabric
          game-versions: |
            1.14.4
            1.15.2
            1.16.5
            1.17.1
            1.18.2
            1.19.2
            1.19.3
            1.19.4

          version-resolver: exact

          retry-attempts: 3
          retry-delay: 10000