name: Publish Release
on:
  release:
    types:
      - published
jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [ 16 ]
        # and run on both Linux and Windows
        os: [ ubuntu-20.04 ]
        branch: [master, 1.16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v2.0
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }}
        with:
          files: 'build/libs/*;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}